/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import config.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;
import modelo.Dueno;
import modelo.Servicio;

public class GenerarBoleta extends javax.swing.JInternalFrame {

    /**
     * Creates new form GenerarBoleta
     */
    double precioFinal = 0.0; // Variable para guardar el total

    public GenerarBoleta() {
        initComponents();
        
        // Configuración de ventana
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Caja / Facturación");
        
        // ¡AQUÍ LLAMAMOS A LOS MÉTODOS PARA LLENAR LAS LISTAS!
        cargarClientes();
        cargarServicios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jbtnGenerarBoleta = new javax.swing.JButton();
        jbtnCalcular = new javax.swing.JButton();
        jcbnCliente = new javax.swing.JComboBox();
        jcbnServicio = new javax.swing.JComboBox();
        jtxtCantidad = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CAJA / FACTURACIÓN");

        jLabel2.setText("Cliente:");

        jLabel3.setText("Servicio:");

        jLabel4.setText("Cantidad:");

        jlblTotal.setText("TOTAL: $0.00");

        jbtnGenerarBoleta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnGenerarBoleta.setText("Generar Boleta");
        jbtnGenerarBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerarBoletaActionPerformed(evt);
            }
        });

        jbtnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnCalcular.setText("Calcular");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });

        jcbnCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbnClienteActionPerformed(evt);
            }
        });

        jcbnServicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consulta General — 30.00", "Vacuna Quintuple — 50.00", "Baño y Corte — 45.00", "Desparasitación — 20.00", "Corte de Uñas — 15.00", "Limpieza Dental — 60.00", "Rayos X — 85.00", "Ecografía Abdominal — 100.00", "Hospedaje Diario — 40.00", "Cirugía de Esterilización — 250.00", "Microchip de Identificación — 120.00", "Análisis de Sangre — 70.00", "Consulta de Emergencia — 60.00", "Tratamiento de Pulgas — 35.00", " ", " " }));
        jcbnServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbnServicioActionPerformed(evt);
            }
        });

        jtxtCantidad.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbnCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbnServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 88, Short.MAX_VALUE)
                        .addComponent(jlblTotal)
                        .addGap(213, 213, 213))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnGenerarBoleta)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jcbnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbnServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnCalcular)
                .addGap(31, 31, 31)
                .addComponent(jlblTotal)
                .addGap(39, 39, 39)
                .addComponent(jbtnGenerarBoleta)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
     try {
        // 1. Obtener Servicio y Precio
        modelo.Servicio servicio = (modelo.Servicio) jcbnServicio.getSelectedItem();
        
        if (servicio == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Selecciona un servicio");
            return;
        }

        // 2. Obtener Cantidad
        if (jtxtCantidad.getText().isEmpty()) {
             javax.swing.JOptionPane.showMessageDialog(null, "Ingresa una cantidad");
             return;
        }
        int cantidad = Integer.parseInt(jtxtCantidad.getText());
        double precioUnitario = servicio.getPrecio();

        // 3. CÁLCULOS PERÚ (IGV 18%) 🇵🇪
        double importeTotal = precioUnitario * cantidad; // Lo que paga el cliente
        double subtotal = importeTotal / 1.18;           // Valor sin IGV
        double igv = importeTotal - subtotal;            // El impuesto

        // 4. Mostrar en la etiqueta (Formato bonito con 2 decimales)
        String texto = String.format("<html>Subtotal: S/. %.2f<br>IGV (18%%): S/. %.2f<br><b>TOTAL A PAGAR: S/. %.2f</b></html>", 
                                     subtotal, igv, importeTotal);
        
        jlblTotal.setText(texto);
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "La cantidad debe ser número entero");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    private void jbtnGenerarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerarBoletaActionPerformed
       Dueno cliente = (Dueno) jcbnCliente.getSelectedItem();
    Servicio servicio = (Servicio) jcbnServicio.getSelectedItem();
    int cantidad = Integer.parseInt(jtxtCantidad.getText());

    String boleta = """
                    ----------- VETERINARIA ------------
                    BOLETA DE VENTA
                    ------------------------------------
                    Cliente: %s
                    Servicio: %s
                    Precio Unit: $%s
                    Cantidad: %d
                    ------------------------------------
                    TOTAL: $%s
                    ------------------------------------
                    ¡Gracias por su visita!
                    """.formatted(cliente.toString(), servicio.getNombre(), servicio.getPrecio(), cantidad, precioFinal);

    JOptionPane.showMessageDialog(null, boleta);
    }//GEN-LAST:event_jbtnGenerarBoletaActionPerformed

    private void jcbnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbnClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbnClienteActionPerformed

    private void jcbnServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbnServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbnServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JButton jbtnGenerarBoleta;
    private javax.swing.JComboBox jcbnCliente;
    private javax.swing.JComboBox jcbnServicio;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables


  // --- MÉTODOS DE CARGA (Para llenar las listas correctamente) ---

    private void cargarClientes() {
        try {
            Connection cn = new Conexion().getConexion();
            // OJO: Aquí pedimos datos a la tabla DUENOS
            String sql = "SELECT * FROM duenos";
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            jcbnCliente.removeAllItems(); // Limpiamos la lista de clientes
            
            while(rs.next()) {
                Dueno d = new Dueno();
                d.setId_dueno(rs.getInt("id_dueno"));
                d.setNombre(rs.getString("nombre"));
                d.setApellidos(rs.getString("apellidos"));
                
                // Lo metemos en la lista jcmbCliente
                jcbnCliente.addItem(d);
            }
        } catch (Exception e) {
            System.out.println("Error cargando clientes: " + e);
        }
    }

    private void cargarServicios() {
        try {
            Connection cn = new Conexion().getConexion();
            // OJO: Aquí pedimos datos a la tabla SERVICIOS
            String sql = "SELECT * FROM servicios";
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            jcbnServicio.removeAllItems(); // Limpiamos la lista de servicios
            
            while(rs.next()) {
                Servicio s = new Servicio();
                s.setId_servicio(rs.getInt("id_servicio"));
                s.setNombre(rs.getString("nombre"));
                s.setPrecio(rs.getDouble("precio")); // Importante traer el precio
                
                // Lo metemos en la lista jcmbServicio
                jcbnServicio.addItem(s);
            }
        } catch (Exception e) {
            System.out.println("Error cargando servicios: " + e);
        }
    }
}
