/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import config.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;
import modelo.Mascota;
import modelo.Servicio;

public class RegistroCita extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroCita
     */
    public RegistroCita() {
        initComponents();
        // Propiedades de la ventana interna
        setClosable(true);
        setIconifiable(true);
        setTitle("Agendar Nueva Cita");
        
        // ¡LLENAR LAS LISTAS AL ABRIR!
        cargarMascotas();
        cargarServicios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbxMascota = new javax.swing.JComboBox();
        jcbxServicio = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jbtnAgendarCita = new javax.swing.JButton();
        jtxtFecha = new javax.swing.JTextField();

        jLabel1.setText("Mascota:");

        jLabel2.setText("Servicio:");

        jcbxMascota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbxServicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Fecha:");

        jbtnAgendarCita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnAgendarCita.setText("Agendar cita");
        jbtnAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgendarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnAgendarCita)
                    .addComponent(jtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxServicio, 0, 198, Short.MAX_VALUE)
                    .addComponent(jcbxMascota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbxMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jbtnAgendarCita)
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgendarCitaActionPerformed
                                                  
        // 1. Validar fecha
        if (jtxtFecha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa la fecha (AAAA-MM-DD)");
            return;
        }

        // 2. RECUPERAR OBJETOS SELECCIONADOS
        Mascota mascotaSeleccionada = (Mascota) jcbxMascota.getSelectedItem();
        Servicio servicioSeleccionado = (Servicio) jcbxServicio.getSelectedItem();

        if (mascotaSeleccionada == null || servicioSeleccionado == null) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un Paciente y un Servicio");
            return;
        }

        // 3. CONECTAR Y GUARDAR
        try {
            Connection cn = new Conexion().getConexion();
            
            // Insertamos en la tabla 'citas'
            String sql = "INSERT INTO citas (fecha_hora, motivo, estado, id_mascota, id_servicio) VALUES (?, ?, ?, ?, ?)";
            
            PreparedStatement pst = cn.prepareStatement(sql);
            
            pst.setString(1, jtxtFecha.getText());       // Fecha
            pst.setString(2, "Cita Programada");        // Motivo automático
            pst.setString(3, "Pendiente");              // Estado inicial
            pst.setInt(4, mascotaSeleccionada.getId_mascota()); // ID Mascota (Oculto en el objeto)
            pst.setInt(5, servicioSeleccionado.getId_servicio()); // ID Servicio (Oculto en el objeto)

            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "¡Cita Agendada con Éxito! 📅");
            jtxtFecha.setText(""); // Limpiar
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al agendar: " + e.getMessage());
        }
    }//GEN-LAST:event_jbtnAgendarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnAgendarCita;
    private javax.swing.JComboBox jcbxMascota;
    private javax.swing.JComboBox jcbxServicio;
    private javax.swing.JTextField jtxtFecha;
    // End of variables declaration//GEN-END:variables

    // --- MÉTODOS DE CARGA (Pégalos al final) ---

    private void cargarMascotas() {
        try {
            Connection cn = new Conexion().getConexion();
            ResultSet rs = cn.prepareStatement("SELECT * FROM mascotas").executeQuery();
            jcbxMascota.removeAllItems();
            
            while(rs.next()) {
                // Creamos el objeto Mascota con sus datos
                Mascota m = new Mascota();
                m.setId_mascota(rs.getInt("id_mascota"));
                m.setNombre(rs.getString("nombre"));
                m.setRaza(rs.getString("raza"));
                
                // Lo agregamos a la lista (se verá su nombre gracias al toString)
                jcbxMascota.addItem(m); 
            }
        } catch (Exception e) { e.printStackTrace(); }
    }

    private void cargarServicios() {
        try {
            Connection cn = new Conexion().getConexion();
            ResultSet rs = cn.prepareStatement("SELECT * FROM servicios").executeQuery();
             jcbxServicio.removeAllItems();
            
            while(rs.next()) {
                Servicio s = new Servicio();
                s.setId_servicio(rs.getInt("id_servicio"));
                s.setNombre(rs.getString("nombre"));
                s.setPrecio(rs.getDouble("precio"));
                
                jcbxServicio.addItem(s);
            }
        } catch (Exception e) { e.printStackTrace(); }
    }

}
