/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author USUARIO
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        // ESTA ES LA LÍNEA MÁGICA ✨
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdkpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuReporte = new javax.swing.JMenu();
        menuVerPacietes = new javax.swing.JMenuItem();
        menuVerCitas = new javax.swing.JMenuItem();
        menuGestion = new javax.swing.JMenu();
        MenuAgendarCita = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        menuNuevoDueño = new javax.swing.JMenuItem();
        menuNuevaMascota = new javax.swing.JMenuItem();
        menuNuevoServicio = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        Login = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        javax.swing.GroupLayout jdkpEscritorioLayout = new javax.swing.GroupLayout(jdkpEscritorio);
        jdkpEscritorio.setLayout(jdkpEscritorioLayout);
        jdkpEscritorioLayout.setHorizontalGroup(
            jdkpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        jdkpEscritorioLayout.setVerticalGroup(
            jdkpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        menuReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list-symbol-of-three-items-with-dots_icon-icons.com_72994.png"))); // NOI18N
        menuReporte.setText("Reporte");

        menuVerPacietes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view_data_icon_215854.png"))); // NOI18N
        menuVerPacietes.setText("Ver pacientes");
        menuVerPacietes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerPacietesActionPerformed(evt);
            }
        });
        menuReporte.add(menuVerPacietes);

        menuVerCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1492790922-20list_84170.png"))); // NOI18N
        menuVerCitas.setText("verCitas");
        menuVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerCitasActionPerformed(evt);
            }
        });
        menuReporte.add(menuVerCitas);

        jMenuBar1.add(menuReporte);

        menuGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backup_1_29638 (1).png"))); // NOI18N
        menuGestion.setText("Gestion ");

        MenuAgendarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agenda_notebook_icon_124098.png"))); // NOI18N
        MenuAgendarCita.setText("Agendar cita");
        MenuAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgendarCitaActionPerformed(evt);
            }
        });
        menuGestion.add(MenuAgendarCita);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        jMenuItem2.setText("Generar Boleta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuGestion.add(jMenuItem2);

        jMenuBar1.add(menuGestion);

        menuRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new_folder_white_13776.png"))); // NOI18N
        menuRegistro.setText("Registro");

        menuNuevoDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new_interface_profile_add_follow_user_icon_259525.png"))); // NOI18N
        menuNuevoDueño.setText("Nuevo Dueño");
        menuNuevoDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoDueñoActionPerformed(evt);
            }
        });
        menuRegistro.add(menuNuevoDueño);

        menuNuevaMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new_insert_database_16696.png"))); // NOI18N
        menuNuevaMascota.setText("Nueva Mascota");
        menuNuevaMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevaMascotaActionPerformed(evt);
            }
        });
        menuRegistro.add(menuNuevaMascota);

        menuNuevoServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shoppaymentorderbuy-51_icon-icons.com_73853.png"))); // NOI18N
        menuNuevoServicio.setText("Nuevo Servicio");
        menuNuevoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoServicioActionPerformed(evt);
            }
        });
        menuRegistro.add(menuNuevoServicio);

        jMenuBar1.add(menuRegistro);

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/systemshutdown_103390.png"))); // NOI18N
        menuSalir.setText("Cerrar Sesion");

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4213459-common-door-exit-logout-out-signout_115411.png"))); // NOI18N
        Login.setText("Salir");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        menuSalir.add(Login);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdkpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdkpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNuevaMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevaMascotaActionPerformed
        RegistroMascota ventana = new RegistroMascota();
    jdkpEscritorio.add(ventana); // O jdtpEscritorio si así se llama
    
    // Centrar
    int x = (jdkpEscritorio.getWidth() - ventana.getWidth()) / 2;
    int y = (jdkpEscritorio.getHeight() - ventana.getHeight()) / 2;
    ventana.setLocation(x, y);
    
    ventana.setVisible(true);
    }//GEN-LAST:event_menuNuevaMascotaActionPerformed

    private void menuNuevoDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoDueñoActionPerformed
        
        
        RegistroDueno ventana = new RegistroDueno();
    jdkpEscritorio.add(ventana); // La metemos al escritorio azul
    
    // Centrarla
    int x = (jdkpEscritorio.getWidth() - ventana.getWidth()) / 2;
    int y = (jdkpEscritorio.getHeight() - ventana.getHeight()) / 2;
    ventana.setLocation(x, y);
    
    ventana.setVisible(true);
    }//GEN-LAST:event_menuNuevoDueñoActionPerformed

    private void menuNuevoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoServicioActionPerformed
        
        
        RegistroServicio ventana = new RegistroServicio();
        jdkpEscritorio.add(ventana); // O jdtpEscritorio

        // Centrar
        int x = (jdkpEscritorio.getWidth() - ventana.getWidth()) / 2;
        int y = (jdkpEscritorio.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);

        ventana.setVisible(true);
    }//GEN-LAST:event_menuNuevoServicioActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// 1. Crear la ventana de Boleta
    GenerarBoleta ventana = new GenerarBoleta();
    
    // 2. Agregarla al escritorio (tu fondo azul)
    jdkpEscritorio.add(ventana);
    
    // 3. Centrarla bonita
    int x = (jdkpEscritorio.getWidth() - ventana.getWidth()) / 2;
    int y = (jdkpEscritorio.getHeight() - ventana.getHeight()) / 2;
    ventana.setLocation(x, y);
    
    // 4. Mostrarla
    ventana.setVisible(true);       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MenuAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgendarCitaActionPerformed
        RegistroCita ventana = new RegistroCita();
    jdkpEscritorio.add(ventana); // Agregar al escritorio azul
    
    // Centrar
    int x = (jdkpEscritorio.getWidth() - ventana.getWidth()) / 2;
    int y = (jdkpEscritorio.getHeight() - ventana.getHeight()) / 2;
    ventana.setLocation(x, y);
    
    ventana.setVisible(true);
    }//GEN-LAST:event_MenuAgendarCitaActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        System.exit(0);      
    }//GEN-LAST:event_LoginActionPerformed

    private void menuVerPacietesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerPacietesActionPerformed
        // 1. Crear la instancia de tu ventana
    verDatos ventana = new verDatos();
    
    // 2. IMPORTANTE: Agregarla al escritorio azul
    // (Asegúrate de que tu escritorio se llame 'jdtpEscritorio' o 'escritorio')
    jdkpEscritorio.add(ventana); 
    
    // 3. Centrarla (Opcional, para que se vea bonita)
    java.awt.Dimension desktopSize = jdkpEscritorio.getSize();
    java.awt.Dimension frameSize = ventana.getSize();
    ventana.setLocation((desktopSize.width - frameSize.width)/2, (desktopSize.height - frameSize.height)/2);
    
    // 4. ¡HACERLA VISIBLE! (Sin esto no sale)
    ventana.setVisible(true);
    }//GEN-LAST:event_menuVerPacietesActionPerformed

    private void menuVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerCitasActionPerformed
        verCitas ventana = new verCitas();
    jdkpEscritorio.add(ventana); // Recuerda usar jdtpEscritorio o escritorio
    
    // Centrar
    int x = (jdkpEscritorio.getWidth() - ventana.getWidth()) / 2;
    int y = (jdkpEscritorio.getHeight() - ventana.getHeight()) / 2;
    ventana.setLocation(x, y);
    
    ventana.setVisible(true);
    }//GEN-LAST:event_menuVerCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Login;
    private javax.swing.JMenuItem MenuAgendarCita;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JDesktopPane jdkpEscritorio;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenuItem menuNuevaMascota;
    private javax.swing.JMenuItem menuNuevoDueño;
    private javax.swing.JMenuItem menuNuevoServicio;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenu menuReporte;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem menuVerCitas;
    private javax.swing.JMenuItem menuVerPacietes;
    // End of variables declaration//GEN-END:variables
}
