/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import config.Conexion;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class verCitas extends javax.swing.JInternalFrame {

    /**
     * Creates new form verCitas
     */
    public verCitas() {
        initComponents();
        
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setMaximizable(true);
        setTitle("Agenda de Citas");
        
        mostrarTabla(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCitas = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); 
        jLabel1.setText("HISTORIAL DE CITAS");

        jtblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblCitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblCitas;
    // End of variables declaration//GEN-END:variables
private void mostrarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        
        // Columnas
        modelo.addColumn("Fecha");
        modelo.addColumn("Mascota");
        modelo.addColumn("Servicio");
        modelo.addColumn("Estado");
        modelo.addColumn("Motivo");
        
        jtblCitas.setModel(modelo);

       
        String sql = "SELECT c.fecha_hora, m.nombre AS mascota, s.nombre AS servicio, c.estado, c.motivo " +
                     "FROM citas c " +
                     "INNER JOIN mascotas m ON c.id_mascota = m.id_mascota " +
                     "INNER JOIN servicios s ON c.id_servicio = s.id_servicio " +
                     "ORDER BY c.fecha_hora DESC"; 
        String[] datos = new String[5];

        try {
            Connection cn = new Conexion().getConexion();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                datos[0] = rs.getString("fecha_hora");
                datos[1] = rs.getString("mascota");
                datos[2] = rs.getString("servicio");
                datos[3] = rs.getString("estado");
                datos[4] = rs.getString("motivo");
                
                modelo.addRow(datos);
            }
            jtblCitas.setModel(modelo);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar citas: " + e.getMessage());
        }
    }

}
