/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import config.Conexion;
import java.sql.*;
import javax.swing.table.DefaultTableModel; 
import javax.swing.JOptionPane;

public class verDatos extends javax.swing.JInternalFrame {

    /**
     * Creates new form verDatos
     */
    public verDatos() {
    initComponents();

   
    setClosable(true);
    setIconifiable(true);
    setResizable(true);
    setMaximizable(true);

    mostrarTabla(); // Carga los datos
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("LISTA DE PACIENTES");

        jtblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblDatos;
    // End of variables declaration//GEN-END:variables
private void mostrarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        // Definimos las columnas que veremos
        modelo.addColumn("ID");
        modelo.addColumn("Mascota");
        modelo.addColumn("Especie");
        modelo.addColumn("Raza");
        modelo.addColumn("Fecha Nac.");
        modelo.addColumn("Dueño");
        
        jtblDatos.setModel(modelo); 

        
        String sql = "SELECT m.id_mascota, m.nombre, m.especie, m.raza, m.fecha_nacimiento, d.nombre " +
                     "FROM mascotas m INNER JOIN duenos d ON m.id_dueno = d.id_dueno";

        String[] datos = new String[6];

        try {
            config.Conexion con = new config.Conexion();
            Connection cn = con.getConexion();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                datos[0] = rs.getString(1); 
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3); 
                datos[3] = rs.getString(4); 
                datos[4] = rs.getString(5); 
                datos[5] = rs.getString(6); 
                modelo.addRow(datos);
            }
            jtblDatos.setModel(modelo); 
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar: " + e.getMessage());
        }
    }

}
